package leongcheewah.invoicemanagement.util

object Constants {
    const val INVOICE_NO = "Invoice No"
    const val STOCK_CODE = "Stock Code"
    const val DESCRIPTION = "Description"
    const val QUANTITY = "Quantity"
    const val INVOICE_DATE = "Invoice Date"
    const val UNIT_PRICE = "Unit Price"
    const val CUSTOMER_ID = "Customer ID"
    const val COUNTRY = "Country"
    const val BAD_INPUT_ERROR = "Invalid "
    const val MISSING_ERROR = "Missing "
    const val DUPLICATE = "Duplicate "
    const val ONGOING_UPLOAD = "Ongoing Upload"
    const val UPLOAD_ERROR = "Upload Failed - "
    const val CSV_FILE_FORMAT_NOT_MATCH = "Invalid CSV file"
    const val CSV_FILE_IS_EMPTY = "Empty CSV file / No Records"
    const val CSV_EXPECTED_HEADERS = "InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country"
    const val CSV_HEADERS_DONT_MATCH_EXPECTED = "CSV headers does not match. Expected: [" + CSV_EXPECTED_HEADERS + "]"
    const val SUCCESS_UPLOAD = "Successfully uploaded"
    const val SUCCESS_CREATE = "Successfully created"
    const val SUCCESS_UPDATE = "Successfully updated"
    const val SUCCESS_DELETE = "Successfully deleted"
    const val ERROR_CREATE = "Error trying to create"
    const val ERROR_UPDATE = "Error trying to update"
    const val ERROR_DELETE = "Error trying to delete"
    const val DATA_ERROR_FAILED_TO_RETRIEVE = "Failed to retrieve list"
    const val RESPONSE_ERROR_CODE = "500"
}